import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
decorations = "Full"
title = "Alacritty"
decorations_theme_variant = "Dark"

[window.padding]
x = 5
y = 2

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.0

[font.normal]
family = "UbuntuMono Nerd Font Mono"

[font.bold]
family = "UbuntuMono Nerd Font Mono"

[font.italic]
family = "UbuntuMono Nerd Font Mono"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" }
]
